### ISSUE TITLE
pyranha import problem

### ISSUE THREAD

**Issue by rwst** [bluescarni/piranha#16]
```
In [1]: import pyranha
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-1b2302a40034> in <module>()
----> 1 import pyranha

/home/ralf/piranha/pyranha/__init__.py in <module>()
     24 
     25 import threading as _thr
---> 26 from ._common import _cpp_type_catcher, _monkey_patching, _cleanup
     27 from ._core import file_format, file_compression
     28 

/home/ralf/piranha/pyranha/_common.py in <module>()
     20 from __future__ import absolute_import as _ai
     21 
---> 22 from . import _core
     23 
     24 # Decorator to prettify the type errors resulting when calling a C++ exposed function

ImportError: pyranha/_core.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE
```
I have `libboost-python-1.54` installed (but maybe not in Py3 where Pyranha wanted to install itself). Sorry I'm a Python amateur and have worked with Py2 until now.

**Comment by bluescarni** [comment]
@rwst can you check please the versions of the Python and boost Python libraries found by CMake? They are available in the CMake GUI's advanced options, among other places.

It happens quite often that CMake finds Python 2.7 and then it tries to link to Boot.Python3.4 instead, or viceversa.

Another point - not sure if it matters: are you trying to import Pyranha from within the build or source directory? I had problems with this in the past, I usually do a ``make install`` and start ipython from another directory usually.

**Comment by rwst** [comment]
Output from `cmake .`:
```
-- Python libraries: /usr/lib64/libpython3.4m.so
-- Python library: /usr/lib64/libpython3.4m.so
-- Python interpreter is: /usr/bin/python
-- Python packages dir is: site-packages
-- Python library version: 34
-- Python modules install path: lib/python3.4/site-packages
```
but
```
lrwxrwxrwx 1 root root 9 May  9 17:17 /usr/bin/python -> python2.7*
```
I imported from a separate directory.

**Comment by rwst** [comment]
I used the method in http://stackoverflow.com/questions/15291500/i-have-2-versions-of-python-installed-but-cmake-is-using-older-version-how-do to work around the cmake problem.

**Comment by bluescarni** [comment]
@rwst Awesome, thanks for figuring this out. I need to update the install doc to make it clear that CMake can be flaky with multiple Python versions.
