### ISSUE TITLE
test failures

### ISSUE THREAD

**Issue by rwst** [bluescarni/piranha#18]
This is with gcc-4.9:

```
The following tests FAILED:
         11 - gastineau2_perf (Failed)
         12 - gastineau3_perf (Failed)
         13 - gastineau4_perf (Failed)
         26 - perminov1_perf (Failed)

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/4.9/lto-wrapper
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada,go --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.9 --enable-ssp --disable-libssp --disable-libvtv --disable-plugin --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --enable-linker-build-id --enable-linux-futex --program-suffix=-4.9 --without-system-libunwind --enable-multilib --with-arch-32=i586 --with-tune=generic --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 4.9.0 (SUSE Linux) 
```

**Comment by bluescarni** [comment]
@rwst Thanks for the report! Would you mind running each test in isolation and reporting what specific error is raised?

My guesses:

- the gastineau tests use lots of memory (tens of gigabytes), it's probably a memory error being raised;
- the perminov test has a known problem: it needs some serialised data which I have serialized using version 1.57 of the Boost libraries, and apparently if your Boost version is less than that you could have problems reading the data (Boost serialization is not forward-compatible unfortunately). Which Boost version are you using?

**Comment by rwst** [comment]
I'm not sure, `gastineau2_perf` immediately stops with:
```
ralf@ark:~/piranha/tests> ./gastineau2_perf 
Running 1 test case...
 0.140504s wall, 0.530000s user + 0.020000s system = 0.550000s CPU (391.4%)
unknown location(0): fatal error in "gastineau2_test": std::bad_alloc: std::bad_alloc
/home/ralf/piranha/tests/gastineau2_perf.cpp(47): last checkpoint

*** 1 failure detected in test suite "gastineau2_test"
Freeing MPFR caches.
```
same with 3 and 4. As to the perminov, I have boost-1.54 libraries indeed. Installing a new one is too much hassle atm.

**Comment by bluescarni** [comment]
@rwst Right, this line:

```
unknown location(0): fatal error in "gastineau2_test": std::bad_alloc: std::bad_alloc
```

Means there was not enough memory to run the test. The second gastineau test takes about 40GB of memory if I recall correctly.

I need to fix the perminov test on my side. Would it be possible for you to paste here its output as well, just to make sure it really is a serialization problem?

**Comment by rwst** [comment]
I only got this:
```
Running 1 test case...
unknown location(0): fatal error in "perminov1_test": std::exception: unsupported version

*** 1 failure detected in test suite "perminov1_test"
Freeing MPFR caches.
```

**Comment by bluescarni** [comment]
@rwst I think that's it, thanks for confirming. I need to re-create the serialised data with an older version of the Boost libraries.

**Comment by bluescarni** [comment]
The Perminov test works now, thanks to the new serialization API (#78). Closing this.
