### ISSUE TITLE
doc: emphasize the pitfalls of CMake's Python detection

### ISSUE THREAD

**Issue by bluescarni** [bluescarni/piranha#23]
It seems like on systems with Pyhon 2 and 3 installed simultaneously CMake often fails either to detect the default Python version or to make sure that Python and Boost.Python versions match. E.g., https://github.com/bluescarni/piranha/issues/16.

We need to make this clearer in the documentation, as it seems be happening fairly often.

**Comment by isuruf** [comment]
If you want the default python version to be found by CMake, add something like,
```
set(PYTHON_EXECUTABLE "python
    CACHE PATH "Path to python executable")
```
Python version pointed by "python" in the session will be found in this case. Downside is, this will break if there is no python in your PATH variable.

**Comment by bluescarni** [comment]
@isuruf I am kind of doing something like that, at least for inferring the install path of the Python modules. The problem seems to be more the consistency between Python version and Boost.Python version.

On my system I have 2 versions of the Boost.Python library installed by my package manager (I am on Gentoo Linux):

```
yardbird@berserk ~ % ls /usr/lib/libboost_python-*
/usr/lib/libboost_python-2.7-mt.so  /usr/lib/libboost_python-2.7.so.1.57.0  /usr/lib/libboost_python-3.4.so
/usr/lib/libboost_python-2.7.so     /usr/lib/libboost_python-3.4-mt.so      /usr/lib/libboost_python-3.4.so.1.57.0
```

Which makes total sense, as I have both Python 2.x and 3.x installed at the same time, so I need 2 versions of the corresponding Boost library (as Python 2.x and 3.x are ABI incompatible). CMake often picks up a version for the Python interpreter and libraries, and another version for Boost.Python. I have seen all sorts of combinations (Python 2.x vs Boost.Python 3.x, viceversa, and sometimes the correct combination is picked). I think the problem stems from the fact that the Boost macros in CMake are not well equipped to deal with Boost.Python coming in multiple variants. It is also highly dependent on the CMake version I think.

I just tried with a fresh checkout on my system. Here, python2.7 is the default one (in the sense that if you type ``python`` in the command line you get python 2), and yet the CMake macros pick up ``python3.4`` as interpreter - but at least they identify correctly that they need to link to ``libboost_python-3.4`` :)

In general, I think the only sensible option is to warn the compiling users that they need to double check what CMake detects Python-wise when they setup the compilation of the Python bindings.

**Comment by isuruf** [comment]
When you don't specify the `PYTHON_EXECUTABLE` then it won't look at the default python version. (i.e. python2 in your case). So if you add a line like I said then the default python version will be found.

For Boost.python it looks only for the default version. Do you have a symlink like `/usr/lib/libboost_python.so` that points to python3 instead of python2?

**Comment by bluescarni** [comment]
Mhm I was under the assumption that out-of-the-box CMake's macro will detect the "default" python from the ``python`` command, as this would seem the most sensible thing to do. This is not the case then? It will pick the latest Python available regardless?

And no, on this system I do not have a ``/usr/lib/libboost_python.so`` symlink - but I would imagine other system configurations might provide it.

**Comment by isuruf** [comment]
Out-of-the-box CMake's `FindPythonInterp.cmake` looks for the latest version unless `PYTHON_EXECUTABLE` is set.

If `PYTHON_EXECUTABLE` is set, it will use that value to call a python shell by doing 
```
execute_process(COMMAND "${PYTHON_EXECUTABLE}" -c
                            "import sys; sys.stdout.write(';'.join([str(x) for x in sys.version_info[:3]]))"
```

If there is no `/usr/lib/libboost_python.so` or `/usr/lib/libboost_python-mt.so` or similar symlink I don't think CMake can find Boost.Python. (If I'm reading `FindBoost.cmake` correctly)

**Comment by bluescarni** [comment]
This is what I get when looking into my ``/usr/lib/``:

```
yardbird@berserk build % ls -lsa  /usr/lib/libboost_python*
  0 lrwxrwxrwx 1 root root     22 Oct  7 15:08 /usr/lib/libboost_python-2.7-mt.so -> libboost_python-2.7.so
  0 lrwxrwxrwx 1 root root     29 Oct  7 15:08 /usr/lib/libboost_python-2.7.so -> libboost_python-2.7.so.1.57.0
320 -rwxr-xr-x 1 root root 323728 Oct  7 15:08 /usr/lib/libboost_python-2.7.so.1.57.0
  0 lrwxrwxrwx 1 root root     22 Oct  7 15:08 /usr/lib/libboost_python-3.4-mt.so -> libboost_python-3.4.so
  0 lrwxrwxrwx 1 root root     29 Oct  7 15:08 /usr/lib/libboost_python-3.4.so -> libboost_python-3.4.so.1.57.0
324 -rwxr-xr-x 1 root root 327952 Oct  7 15:08 /usr/lib/libboost_python-3.4.so.1.57.0
```

So it looks like all libraries are versioned.

**Comment by isuruf** [comment]
Ah. gentoo has a patch for CMake which looks for `libboost_python-${python_version}` which finds `${python_version}` using `PYTHON_EXECUTABLE`. So at least in gentoo it's impossible to get two different python versions for Python and Boost.Python.

For others like Debian, you'll have to have a workaround by using something like `find_package(Boost components python-py${python_version} python-${python_version}`

**Comment by bluescarni** [comment]
Ahh good catch, thanks for figuring that out. Jesus. It does seems something sensible to do, as Gentoo has a policy of allowing different major Python versions to be installed simultaneously, and so they have the problem of dealing with Python-dependent libraries linked against different Python versions. So instead of going with a default Boot.Python library, they version everything so when installing a Python-dependent package you can easily build multiple versions of it.

Still, it seems like this will make it even harder to solve the issue cleanly and generically on our side.
