### ISSUE TITLE
Exception message improvement in piranha::polynomial::extend_symbol_set

### ISSUE THREAD

**Issue by darioizzo** [bluescarni/piranha#37]
Right now if the argument does not pass all checks the following message is thrown :"invalid symbol set passed to extend_symbol_set()" 

Most of the times though (at least for me), this comes from the fact that the requirement that the arg must contain all already existing symbols is not met due to the user (again, me) forgetting about some.

Could this be changed into: "invalid symbol set passed to extend_symbol_set(); did you forget to  also include all already existing symbols in the symbol_set passed as argument?" 

This would be particularly useful when using piranha from (for example) python.

**Comment by bluescarni** [comment]
Fixed as part of #62.
