### ISSUE TITLE
Problem building archived version v0.2

### ISSUE THREAD

**Issue by jppelteret** [bluescarni/piranha#79]
I'm putting together a package for the [Spack package manager](https://github.com/LLNL/spack). Although the development version from git installs fine, I've hit a configuration error when building the archived version `v0.2`. Attached is a [build log](https://github.com/bluescarni/piranha/files/504424/spack-build.txt), and the salient error lines are:

```
fatal: Not a git repository (or any of the parent directories): .git
CMake Error at CMakeLists.txt:148 (STRING):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
```

Presumably `${PIRANHA_GIT_VERSION}` is undefined in this scenario?

**Comment by bluescarni** [comment]
@jppelteret I think you are right, the problem here is that the CMake script assumes that it is being run from a cloned git repo but of course in case of a tar gz source release that's a false assumption. It's something I should've tested myself, sorry about that.

I'll push out another release in the weekend with a fix, thanks for reporting the problem.

**Comment by jppelteret** [comment]
Great, thanks very much!

**Comment by bluescarni** [comment]
@jppelteret I pushed a new 0.4 release that should build cleanly now. Let me know if it works for you:

https://github.com/bluescarni/piranha/releases/tag/v0.4

**Comment by bluescarni** [comment]
@jppelteret I have also bumped up the minimum cmake version to 3.0.0, I hope it's not an issue. In the medium term I will probably bump it further up to 3.2 or so, as part of a move to a more modern cmake style.

**Comment by jppelteret** [comment]
Thanks @bluescarni , I've added the new version to the `spack` package and have upgraded the requirements for `cmake`. This isn't a problem because `spack` offers an up-to-date version of `cmake`.

Unfortunately I've run into some C++ related difficulties building this version that weren't there last time I built the development version. Here's the attached logs. I think these headers might all be `C++11`, so perhaps there's a `-std=c++11` missing in the compiler flags?
[Failed v0.4 build](https://github.com/bluescarni/piranha/files/510079/spack-build.out.txt)
[Successful build from git master on 3 Oct](https://github.com/bluescarni/piranha/files/510084/build.out.txt)

**Comment by isuruf** [comment]
See #82

**Comment by jppelteret** [comment]
Thanks @isuruf . I'll wait for your PR to be merged before testing again.

**Comment by bluescarni** [comment]
@jppelteret I merged @isuruf's PR and made a new release, 0.5:

https://github.com/bluescarni/piranha/releases/tag/v0.5

Let me know if it works.

**Comment by jppelteret** [comment]
Sorry, @bluescarni , but unfortunately there's new error thats cropped up! Here's the [build log](https://github.com/bluescarni/piranha/files/511063/spack-build.out.txt) and the [error log](https://github.com/bluescarni/piranha/files/511064/CMakeError.log.txt) generated by CMake. If you can point me towards what you think the issue might be, I could try to fix it on my side and make another PR for you to test.

**Comment by jppelteret** [comment]
I forgot to say that this error occurs for both `v0.5` and the git master branch.

**Comment by bluescarni** [comment]
@jppelteret 

Does commenting this out helps?

https://github.com/bluescarni/piranha/blob/79c818e939e9f8d6567b9ba7dd925dc663d2d302/cmake_modules/PiranhaPlatformSettings.cmake#L64

**Comment by bluescarni** [comment]
The error message in the CMake log says:

``clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)``

@isuruf how do you set up the standard library flag in OSX for symengine?

**Comment by isuruf** [comment]
We don't. Since piranha and symengine needs C++11, libc++ needs to be used. libstdc++ shipped in Mac is too old. Therefore MACOSX_DEPLOYMENT_TARGET should be set to 10.7 or above which has libc++. It seems spack by default sets it to 10.5.

**Comment by jppelteret** [comment]
@bluescarni Yes that removed the problem in the configuration stage but left me back with the C++ related issues.

**Comment by jppelteret** [comment]
@bluescarni @isuruf I think I may have been building from a terminal with a polluted environment :-/ I'm starting a new one and will try to rebuild from scratch

**Comment by bluescarni** [comment]
@isuruf any hints on where that variables (DEPLOYMENT_TARGET) should be set? I tried to search for it (and other OSX related vars) in the symengine repo but could not find it.

**Comment by jppelteret** [comment]
One user error was removed from the equation, everything works fine :-) Thanks a lot to you both for your time and patience! Its much appreciated.

**Comment by isuruf** [comment]
@bluescarni, `MACOSX_DEPLOYMENT_TARGET` is an environment variable that a user may set. You can check that `CMAKE_OSX_DEPLOYMENT_TARGET` is set 10.7 or higher if compiler is `AppleClang` and issue an error if not.
