### ISSUE TITLE
How to initialize `integer` from `mpz_class`

### ISSUE THREAD

**Issue by certik** [bluescarni/piranha#9]
I can't figure out how to initialize `integer` from `mpz_class`.

**Comment by certik** [comment]
Here is what I did:
```c++
piranha::integer{coef.get_str()}
```
But obviously that's not optimal.

**Comment by bluescarni** [comment]
Currently the ``integer`` class provides some code to extract an ``mpz_t`` but not the other way around yet. It should be rather easy to implement, let me give it a go and I will ping you back.

**Comment by certik** [comment]
Any progress on this? @Sumith1896 hit the same issue with SymEngine.

**Comment by Sumith1896** [comment]
@bluescarni How do I extract `mpz_t` for `integer` class that you mention?

**Comment by bluescarni** [comment]
@Sumith1896 I replied on gitter, let me know if you need more help.

**Comment by bluescarni** [comment]
@Sumith1896 @certik I committed the constructor from ``mpz_t`` to the master branch, let me know if it works for you.

**Comment by Sumith1896** [comment]
@bluescarni This works. Thanks
I think this can be closed .
